import { Link } from 'react-router-dom';
import { Card } from '../components/ui.jsx';

export default function Disclaimer() {
  return (
    <div className="space-y-3">
      <header className="px-1">
        <h1 className="text-xl font-bold">Disclaimer</h1>
      </header>

      <Card>
        <p className="text-sm text-ink-2">
          Academy Ready is a personal training tracker. It is not medical advice, and nothing in it
          comes from a doctor, a dietitian, or the Akron Police Department.
        </p>
        <ul className="mt-3 space-y-2 text-sm text-ink-2">
          <li className="flex gap-2">
            <span aria-hidden="true" className="text-muted">·</span>
            <span>
              You are on a GLP-1 medication. Keep your prescriber in the loop on training load, food
              intake, and how fast the weight is coming off. The pace flags in this app are a prompt
              to call them, not a substitute for it.
            </span>
          </li>
          <li className="flex gap-2">
            <span aria-hidden="true" className="text-muted">·</span>
            <span>
              Stop and get checked out for chest pain, unusual shortness of breath, dizziness,
              fainting, or pain that is sharp rather than sore.
            </span>
          </li>
          <li className="flex gap-2">
            <span aria-hidden="true" className="text-muted">·</span>
            <span>
              The OPOTC numbers stored here are a training reference. Confirm the current standards
              and your test date with the department before you count on them.
            </span>
          </li>
          <li className="flex gap-2">
            <span aria-hidden="true" className="text-muted">·</span>
            <span>
              Meal plans are generated by a language model. Check them against your own allergies,
              medications, and budget before you shop.
            </span>
          </li>
        </ul>
      </Card>

      <Link to="/settings" className="btn-ghost w-full inline-flex justify-center">
        Back to settings
      </Link>
    </div>
  );
}
